# Generated by Django 5.2.7 on 2025-10-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HS", "High School"),
                    ("DP", "Diploma"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("PhD", "Doctorate"),
                ],
                default="HS",
                max_length=4,
                null=True,
                verbose_name="Education",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="e.g. Computer Science, Business Administration, Engineering",
                max_length=100,
                null=True,
                verbose_name="Specialization",
            ),
        ),
    ]
