# Generated by Django 5.2.7 on 2025-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_birth_date_alter_user_education_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="recommendations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recommendations"
            ),
        ),
    ]
