# Generated by Django 5.2.7 on 2025-11-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Branch"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                default="TM00001",
                max_length=20,
                unique=True,
                verbose_name="Employee ID",
            ),
            preserve_default=False,
        ),
    ]
