# Generated by Django 5.2.7 on 2025-10-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="about_us/", verbose_name="Image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=120, null=True, verbose_name="Full Name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, null=True, verbose_name="Phone Number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Event Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Public"),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="MainInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/", verbose_name="Image"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
            ],
            options={
                "verbose_name": "Website Main Info",
                "verbose_name_plural": "Website Main Info",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="services/", verbose_name="Image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="HomePageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="headers/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Setting it to false, makes the image disappear from the page",
                        verbose_name="Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Order By"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                (
                    "info",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="header_images",
                        to="info.maininfo",
                        verbose_name="Website Main Info",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page Image",
                "verbose_name_plural": "Home Page Images",
                "ordering": ("order", "-create_at", "-update_at"),
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("instagram_2", "Instagram 2"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("waze", "Waze"),
                            ("phone_number_1", "Phone Number 1"),
                            ("phone_number_2", "Phone Number 2"),
                        ],
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Link / Phone Number"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create At"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update At"),
                ),
                (
                    "info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="info.maininfo",
                        verbose_name="Website Main Info",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "ordering": ("-create_at", "-update_at"),
            },
        ),
    ]
