# Generated by Django 5.2.7 on 2025-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="title_ar",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="event",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="event",
            name="location_ar",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="maininfo",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="maininfo",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="maininfo",
            name="title_ar",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="maininfo",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="title_ar",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="service",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Title"),
        ),
    ]
