# Generated by Django 5.2.7 on 2025-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_aboutus_description_ar_aboutus_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
